version: "3.7"

volumes:
  web_data:



services:
  react:
    container_name: react
    build:
      context: ./react1
      dockerfile: Dockerfile
    volumes:
      - web_data:/app/build:rw


  nginx:
    container_name: ngnix
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx
    ports:
      - "8022:80"
    volumes:
      - web_data:/usr/share/nginx/html:ro

